"""Structured output schema for case-outcome reasoning (CLAUDE-2.md capability
2): issues -> arguments per side -> supporting authorities -> per-issue
assessment -> overall position. Structured output, not free prose, so each
step is independently auditable and the faithfulness checks below have
something concrete to validate against."""

from dataclasses import dataclass, field

from pydantic import BaseModel, Field

from policy_advisor.generation.web_search import WebSearchCitation

# The vocabulary the chain assigns to each issue. Constants rather than inline
# strings because the advisory layer and the CI invariant checks both branch on
# them, and a typo in either place would silently stop protecting anything.
CONFIDENCE_STRONG = "strongly supported"
CONFIDENCE_LIMITED = "plausible, limited authority"
CONFIDENCE_NO_AUTHORITY = "no authority found in corpus"
CONFIDENCE_UNVERIFIED = "unverified - flagged by faithfulness check"
CONFIDENCE_FROM_WEB = "from official web sources - not verified against this matter"


class Authority(BaseModel):
    locator: str = Field(description="The exact locator of the cited passage, e.g. 'Order 5 Rule 3' or 'Paragraph 11'")
    relevance: str = Field(description="One sentence on why this authority supports the argument")


class Argument(BaseModel):
    side: str = Field(description="Which side this argument supports, e.g. 'claimant' or 'respondent'")
    summary: str = Field(description="The argument itself, in plain terms")
    supporting_authorities: list[Authority] = Field(default_factory=list)


class IssueArguments(BaseModel):
    """One issue's raw arguments, as generated by Claude - confidence and any
    failure flag are added afterward by the chain, not generated by the model,
    so calibration language can't be gamed or omitted by a bad generation."""

    issue: str
    arguments: list[Argument]
    assessment: str = Field(description="Reasoned analysis of which side's position is better supported and why")


class IssueAnalysis(BaseModel):
    issue: str
    arguments: list[Argument]
    assessment: str
    confidence: str  # one of the CONFIDENCE_* constants below
    unverified: bool = False  # set True if a citation failed both the check and one corrective retry

    # Populated only when this matter held no relevant authority for the issue
    # and the official-sources fallback was allowed. Kept in their own fields
    # rather than folded into `arguments`/`supporting_authorities` on purpose:
    # everything in those has been through the citation check against passages
    # the lawyer put in the matter, and web material has not. Merging the two
    # would make an unvetted source indistinguishable from a vetted one.
    web_summary: str | None = None
    web_sources: list[WebSearchCitation] = Field(default_factory=list)

    @property
    def from_web(self) -> bool:
        return bool(self.web_sources)


class CaseReasoningResult(BaseModel):
    case_facts: str
    issues: list[IssueAnalysis]
    overall_position: str
    disclaimer: str


@dataclass
class StepCheckOutcome:
    faithful: bool
    unsupported_citations: list[str] = field(default_factory=list)
    judge_flagged: bool = False
    judge_notes: str = ""
